pool:
  vmImage: ubuntu-latest

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'DEVSECOPS-USACH'
    organization: 'rsanzana-devsecops-usach'
    projectKey: 'RSANZANA-DEVSECOPS-USACH_pet-clinic'
    projectName: 'pet-clinic'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: "sonarqube"
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
  displayName: 'Analyze current Branch'

- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'DEVSECOPS-USACH'
    organization: 'rsanzana-devsecops-usach'
